# Generated by Django 2.1.5 on 2019-02-08 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('limnstageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='images',
            field=models.FileField(blank=True, upload_to='limnpics'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='profilepic',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to='profilepics'),
            preserve_default=False,
        ),
    ]
