# Generated by Django 2.1.5 on 2019-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limnstageapp', '0002_auto_20190208_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='asked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askeduser', models.CharField(max_length=30)),
                ('limnid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='limnanswer',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='limn',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
